! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : 
	"This is a list widget with the following\ncharacteristics:" &
	"\n\n   - width is 150, height is 200\n   - background is navy\n   " &
	"- items are \n     item1, item2, item3, item4, item5\n   - itemCount" &
	" is 5\n   - visibleItemCount is 5\n   - automaticSelection is true\n" &
	"   - selectionPolicy is \n     XmBROWSE_SELECT\n" &
	"   - fontList is variable\n" &
	"   - listMarginWidth is 50\n   - listMarginHeight is 50\n" &
	"   - browseSelectionCallback is ON\n" &
	"   - defaultActionCallback is ON\n" &
	"\nAll other reources are set by default.\n" &
	"\nThe list forward references the list of\n"&
	"itmes used and the color navy.\n";
