# Generate widget_classes.h, the table of widget classes for the Widgets
# suite, from the public Xm headers: every "extern WidgetClass xm...;" or
# "externalref WidgetClass ...;" declared in a header that is not a
# private (*P.h) or internal (*I.h) one.  New widgets are picked up
# without editing the test.
#
# Run at build time with cmake -P, with -DMOTIF_XM_SOURCE_DIR=...,
# -DMOTIF_WIDGET_CLASSES_OUT=... and -DMOTIF_WIDGET_CLASSES_EXCLUDE=...
# (header names to leave out, separated by commas).

# A script run with -P starts without policies; if(IN_LIST) needs CMP0057.
cmake_minimum_required(VERSION 3.16)

file(GLOB _headers ${MOTIF_XM_SOURCE_DIR}/*.h)
list(SORT _headers)
string(REPLACE "," ";" MOTIF_WIDGET_CLASSES_EXCLUDE "${MOTIF_WIDGET_CLASSES_EXCLUDE}")

set(_includes "")
set(_entries "")
foreach(_header IN LISTS _headers)
    get_filename_component(_name ${_header} NAME)
    if(_name MATCHES "(P|I)\\.h$" OR _name IN_LIST MOTIF_WIDGET_CLASSES_EXCLUDE)
        continue()
    endif()
    file(STRINGS ${_header} _decls
        REGEX "^[ \t]*(extern|externalref)[ \t]+WidgetClass[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*;")
    if(NOT _decls)
        continue()
    endif()
    string(APPEND _includes "#include <Xm/${_name}>\n")
    foreach(_decl IN LISTS _decls)
        string(REGEX REPLACE ".*WidgetClass[ \t]+([A-Za-z0-9_]+).*" "\\1" _class "${_decl}")
        string(APPEND _entries "\t{ \"${_class}\", &${_class} },\n")
    endforeach()
endforeach()

set(_content "/* Generated by widget_classes.cmake from the public Xm headers. */
#ifndef WIDGET_CLASSES_H
#define WIDGET_CLASSES_H

#include <X11/Intrinsic.h>
#include <X11/Shell.h>
${_includes}
struct widget_class {
\tconst char *name;
\tWidgetClass *cls;
};

static const struct widget_class widget_classes[] = {
${_entries}};

#endif /* WIDGET_CLASSES_H */
")

# configure_file() only touches the output when it changes, so the test
# is not rebuilt for nothing on every configure.
file(WRITE ${MOTIF_WIDGET_CLASSES_OUT}.in "${_content}")
configure_file(${MOTIF_WIDGET_CLASSES_OUT}.in ${MOTIF_WIDGET_CLASSES_OUT} COPYONLY)
