/*
 * WARNING: This file is overwritten at code generation time.
 * Any changes to this file will be lost.
 */
/*
 *
 * This constant file generated by Builder Xcessory 3.5.1.
 *
 */
#ifndef creation_H
#define creation_H
#define allviewpix	allviewpix_icon
static char * allviewpix_icon[] = {
"24 24 3 1",
". c #c0cc0cc0c",
"X c #000",
"o c #6363b8b8ffff",
".....XXXXX....XXXXX.....",
"...XXoooooXXXXoooooXX...",
"..XooooooooXXooooooooX..",
".XoXXXooooXooXooooXXooX.",
".XoXooXoooXooXoooXooXoX.",
"XooXooXooXooooXooXoooooX",
"XooXXXoooXooooXoooXXoooX",
"XooXoooooXooooXoooooXooX",
"XooXoooooXooooXooXooXooX",
"XooXoooooXXXXXXoooXXoooX",
".XooooooXXXooXoXXoooooX.",
".XoooooXooXooXoooXooooX.",
"..XoooXooooXXoooooXooX..",
"...XXoXoooXXXXooooXXX...",
".....XXXXXooooXXXXXX....",
".....XoooooooooooooX....",
".....XoooXoooooXoooX....",
".....XoooXXoooXXoooX....",
".....XoooXoXoXoXoooX....",
"......XooXooXooXooX.....",
"......XooXoooooXooX.....",
".......XoooooooooX......",
"........XXoooooXX.......",
"..........XXXXX........."
};


extern Widget Createform(Widget parent);

/*
 * Convenience functions from utilities file (bxutils.c).
 */
extern void RegisterBxConverters(XtAppContext);
extern XtPointer CONVERT(Widget, char *, char *, int, Boolean *);
extern XtPointer DOUBLE(double);
extern XtPointer SINGLE(float);
extern void MENU_POST(Widget, XtPointer, XEvent *, Boolean *);
extern Pixmap XPM_PIXMAP(Widget, char**);
extern void SET_BACKGROUND_COLOR(Widget, ArgList, Cardinal*, Pixel);
extern Widget BxFindTopShell(Widget);
extern WidgetList BxWidgetIdsFromNames(Widget, char*, char*);

/*
 * Callbacks from callbacks.c.
 */
extern void BxExitCB(Widget, XtPointer, XtPointer);
extern void BxSetValuesCB(Widget, XtPointer, XtPointer);
#endif
