#!/bin/sh
#
# Run one static analyser over Motif and ratchet its findings against the
# committed baseline in tools/dev/env/ci/baselines/<tool>.txt (see
# ratchet.py: new findings fail, fixed ones ask for the baseline to be
# lowered).  Run it from the top of the source tree.
#
# Usage: static-analysis.sh clang-tidy|scan-build|cppcheck BUILD_DIR OUT_DIR
#
#   clang-tidy  uses .clang-tidy and BUILD_DIR/compile_commands.json; the
#               tree in BUILD_DIR is built first for the generated headers.
#   scan-build  configures and builds BUILD_DIR (which must not exist yet)
#               under scan-build --status-bugs.  The HTML reports go to
#               OUT_DIR/scan-build.  While the baseline is not empty
#               --status-bugs always fails, so the gate is the ratchet.
#   cppcheck    uses BUILD_DIR/compile_commands.json and writes
#               OUT_DIR/cppcheck.xml.
#
# The counts are written to OUT_DIR/<tool>.txt.  With UPDATE_BASELINE=1
# they are also copied over the baseline.  CMAKE_ARGS is passed to the
# configure steps, which use $CC (default: clang).

set -eu

if [ $# -ne 3 ]; then
  echo "usage: $0 clang-tidy|scan-build|cppcheck BUILD_DIR OUT_DIR" >&2
  exit 2
fi
tool=$1
build=$2
out=$3
here=$(cd "$(dirname "$0")" && pwd)
jobs=$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)
: "${CMAKE_ARGS:=}"
: "${CC:=clang}"
export CC
mkdir -p "$out"

configure() {
  # shellcheck disable=SC2086 # CMAKE_ARGS is a list
  "$@" cmake -S . -B "$build" -G Ninja -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_TESTS=OFF -DWITH_DEMOS=OFF \
    -DWITH_DOCS=OFF $CMAKE_ARGS
}

case "$tool" in
  clang-tidy)
    [ -f "$build/compile_commands.json" ] || configure
    cmake --build "$build" --parallel "$jobs"
    rc=0
    # Only Motif's own sources, not the lexers and parsers generated into
    # the build tree.
    "${RUN_CLANG_TIDY:-run-clang-tidy}" -p "$build" -j "$jobs" -quiet \
      "^$(pwd)/src/" >"$out/clang-tidy.log" 2>&1 || rc=$?
    echo "run-clang-tidy exited with status $rc"
    python3 "$here/ratchet.py" collect clang-tidy . "$build" "$out/clang-tidy.log" \
      >"$out/clang-tidy.txt"
    ;;
  scan-build)
    if [ -e "$build" ]; then
      echo "static-analysis.sh: $build exists; scan-build needs a fresh build tree" >&2
      exit 2
    fi
    # ccache would answer from its cache and skip the analysis.
    CCACHE_DISABLE=1
    export CCACHE_DISABLE
    configure scan-build --use-cc="$CC"
    rc=0
    scan-build --use-cc="$CC" --status-bugs -o "$out/scan-build" \
      --exclude "$build" \
      cmake --build "$build" --parallel "$jobs" >"$out/scan-build.log" 2>&1 || rc=$?
    tail -n 5 "$out/scan-build.log"
    echo "scan-build --status-bugs exited with status $rc"
    # --status-bugs hides the build's own status when there are bugs, so
    # make sure the build actually completed (this is a no-op if it did).
    if ! cmake --build "$build" --parallel "$jobs" >/dev/null 2>&1; then
      echo "static-analysis.sh: the build under scan-build failed" >&2
      exit 1
    fi
    python3 "$here/ratchet.py" collect scan-build . "$build" "$out/scan-build" \
      >"$out/scan-build.txt"
    ;;
  cppcheck)
    [ -f "$build/compile_commands.json" ] || configure
    cmake --build "$build" --parallel "$jobs"
    rc=0
    cppcheck --project="$build/compile_commands.json" -j "$jobs" --quiet \
      --enable=warning,portability --inline-suppr \
      --suppress=missingIncludeSystem --suppress=unmatchedSuppression \
      -i"$build" --xml --xml-version=2 2>"$out/cppcheck.xml" || rc=$?
    echo "cppcheck exited with status $rc"
    python3 "$here/ratchet.py" collect cppcheck . "$build" "$out/cppcheck.xml" \
      >"$out/cppcheck.txt"
    ;;
  *)
    echo "static-analysis.sh: unknown tool '$tool'" >&2
    exit 2
    ;;
esac

baseline=$here/baselines/$tool.txt
if [ "${UPDATE_BASELINE:-0}" = 1 ]; then
  {
    echo "# $tool findings per file and check, see tools/dev/env/ci/ratchet.py."
    echo "# Generated by tools/dev/env/ci/static-analysis.sh with UPDATE_BASELINE=1."
    cat "$out/$tool.txt"
  } >"$baseline"
fi
python3 "$here/ratchet.py" compare "$baseline" "$out/$tool.txt"
