! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This widget is a Bulletin Board Dialog \nwith the following characteristics:\n\n   -" &
	" width is 380\n   - height is 100\n   - background is gold\n   - topShadowColor is " &
	"blue\n   - allowOverlap is false\n   - autoUnmanage is false\n   - dialog title is:" &
	"\n     'This is a Dialog Title (2 Segments)'\n\nAll other resources are set by default.\n";
