! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This widget is a cascade button with\nthe following characteristics:\n\n" &
	"   - there are two Pushbuttons, one\n     is contained within a menuBar\n     and the other is a child of a\n" &
	"     Pulldown Menu. Each cascadeButton\n     has a Pulldown Menu associated with\n     it\n" &
	"   - each Pushbutton has a accelerator\n     and acceleratorText associated\n     with it\n" &
	"   - each PushButton has a mnemonic\n     corresponding to the first\n     character of the PushButton\n" &
	"   - borderWidth is 2\n   - height is 50\n   - width is 100\n   - borderColor is brow" &
	"n\n   - mappingDelay is" &
	" 10\n   - recomputeSize is false\n\nAll other resources are by default.\n";
