! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a comboBox with the \nfollowing characteristics:\n\n"&
"   - navigation is TAB_GROUP\n   - shadowThickness is 5\n   - fontList is" &
" 8x13bold\n   - items is a list of 10\n   - itemCount is 10\n  " &
" - visibleItemCount is 7\n   - columns is 10\n   - positionMode is" &
" ONE_BASED\n   - background is green\n   - foreground is red\n\n\n" &
"All other resources are set by default.\n";















