! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : 
	"This is a Message Box in a Dialog Shell with\nthe following characteristics:\n\n" &
	"   - XmNx is 50\n   - XmNy is 50\n   - XmNallowShellResize is true\n" &
	"   - background color (MessageBox) is yellow\n" &
	"   - foreground color (MessageBox)is red\n" &
	"   - shadowThickness (MessageBox) is 5\n" &
	"   - okCallback (MessageBox) is ON\n" &
	"   - helpCallback (MessageBox) is ON\n" &
	"   - cancelCallback (MessageBox) is ON\n" &
	"   - autoUnmanage (MessageBox) is false\n" &
	"   - messageString (MessageBox) is\n" &
	"     A Message Box in a Dialog Shell\n" &
	"     created in UIL\n\n" &
	"All other resources are set by default.\n";
