! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a FormDialog with the following\ncharcteristics:\n\n" &
"   - width is 250\n   - height is 250\n   - background is b" &
"lue\n   - dialogTitle is The Form Dialog\n" &
"   - The form has six PushButtons.\n   - Callbacks are ON for all.\n" &
"   - PushButton1 is attached to form on\n     the BOTTOM, LEFT, and RIGHT.\n" &
"   - PushButton2 is attached to form on\n     the RIGHT and LEFT, and attached\n     to PB1 on the bottom.\n" &
"     rightOffset and leftOffset is 100\n" &
"   - PushButton3 is attached to form on\n     the RIGHT, attached to PB2 on the\n     BOTTOM, attached to PB5 on the TOP.\n" &
"   - PushButton4 is attached to form on\n     the LEFT, attached to PB2 on the\n     BOTTOM, attached to PB5 on the TOP.\n" &
"   - PushButton5 is attached to form on\n     the RIGHT and LEFT, and attached to\n     PB6 on the TOP.\n" &
"     rightOffset and leftOffset is 100\n" &
"   - PushButton6 is attached to form on\n     the TOP, RIGHT, and LEFT.\n" &
	"\n\nAll other resources are set by default.\n";
