! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a form widget with the following\ncharacteristics:\n\n   - width and height" &
	" is 150\n   - borderWidth is 15\n" &
	"   - defaultPosition is false\n   - allowOverlap is false\n   - rubberPositioning is true\n" &
	"   - The form contains four pushButtons\n     the right PB is attached on the\n" &
	"     TOP, BOTTOM, and on the RIGHT,\n     the left PB is attached on the\n" &
	"     TOP, BOTTOM, and on the LEFT,\n     the top PB is attached on the\n" &
	"     the TOP, RIGHT, and on the LEFT,\n     the bottom PB is attached on the\n" &
	"     the BOTTOM, RIGHT, and on the LEFT.\n" &
	"   - Callback is ON for all PushButtons\n" &
	"\nAll other resources are set by default.\n";
