! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a FileSelectionBox widget with\nthe following characteristics:\n\n   - help" &
	"Callback is on\n   - selectionLabelString is\n     Select a File\n" &
	"   - cancelLabelString is Quit\n   - helpLabelStr" &
	"ing is Info\n   - cancel Callback is ON\n   - filterCallback is ON\n" &
	"   - listUpdated is false\n\n" &
	"Automatically Created Widget Resources:\n\n" &
	"   - All auto widgets have 3 pixel shadow\n" &
	"   - Text widgets are green in background\n" &
	"     and red in foreground.\n" &
	"   - List widgets are wheat in background\n" &
	"   - Most labels (unless specified above)\n" &
	"     have Auto prepended to labelString\n" &
	"   - all scrollbars are yellow in background\n" &
	"   - Separator is double-dashed line\n\n" &
	"All other resources are set by default.\n";
