
! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This test should be displayed on both a color and a monochrome screen for full coverage.\n\n" &
	"Two icon gadgets appear, each the container.\n " &
	"  - the left icon gadget is a pallette with a white on\n" &
	"    wheat label.\n" &
	"  - the right icon gadget is a board with a gray and blue\n" &
	"    line pattern with a white on wheat label.\n" &
   "Selecting either icon or label should cause the the label background" &
   " to turn red, signifying that it is selected.\n" &
   "Dragging and dropping either icon or label should reposition the icon" &
   " gadget in the container.\n";





