! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message :	"This is a list widget with the following\n" &
			"characteristics:\n\n" &
			"   - height is 300\n" &
			"   - width is 100\n" &
			"   - background is black\n" &
			"   - items are\n" &
			"     item1, item2, item3, item4, item5,\n" &
			"     item6, item7\n" &
			"   - itemCount is 7\n" &
			"   - visibleItemCount is 5\n" &
			"   - automaticSelection is true\n" &
			"   - selectionPolicy is \n" &
			"     XmEXTENDED_SELECT\n" &
			"   - extendedSelectionCallback is ON\n" &
			"   - defaultActionCallback is ON\n\n" &
			"All other resources are set by default.\n";
