! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a menuBar with the following\ncharacteristics:\n\n   - background is green\n" &
	"   - borderWidth is 50\n   - borderColor is mediumBlue\n" &
	"   - width is 200\n   - height is 100\n" &
	"   - shadowThickness is 5\n   - bottomshadowColor is navy\n" &
	"   - entryAlignment is\n     XmALIGNMENT_CENTER\n" &
	"   - packing is XmPACK_COLUMN\n   - marginWidth, marginHeight are 10\n" &
	"   - valueChangedcallback is ON\n     for toggleButtons\n" &
	"   - armCallback is ON for\n     pushbuttons\n" &
!	"   - background of TearOffButtons in\n" &
!	"     both Pulldowns should be wheat\n" &
	"   - tearOffModel is XmTEAR_OFF_ENABLED\n" &
	"     for both Pulldown Menus\n" &
	"   - tearOffMenuActivateCallback and\n" &
	"     tearOffMenuDeactivateCallback are\n" &
	"     ON for both Pulldown Menus\n\n" &
	"Automatically created widget resources:\n\n" &
	"   - background of PulldownMenu 1's tearOff\n" &
	"     control is wheat\n" &
	"   - background of PulldownMenu 2's tearOff\n" &
	"     control is red\n" &
	"   - tearOff control has 2 pixel shadow\n" &
	"   - tearOff control has separatorType of\n" &
	"     XmDOUBLE_DASHED_LINE\n\n" &
	"All other resources are set by default.\n";
