! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a PopupMenu with the following\ncharacteristics:\n\n" &
	 	  "   - Menu consists of four pushbuttons.\n" &
		  "   - menuPost is <Btn1Down>\n" &
		  "   - menuAccelerator is <Ctrl>Z\n" &
		  "   - fontList is 8x13bold\n" &
		  "   - accelerators are associated with\n     each pushbutton. Order is:\n     ^A, ^B, ^C, ^D\n" &
		  "   - acceleratorText is associated with\n     each pushbutton. Order is:\n" &
		  "     <Ctrl>A, <Ctrl>B, <Ctrl>C, <Ctrl>D\n" &
		  "   - activateCallback is associated with \n     the pushbuttons\n" &
		  "   - background for popup_menu is \n     forest green\n\n" &
		  "You should be able to traverse the popup\nmenu via the keyboard.\n" &
		  "\nAll other resources are set by default\n";

