! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a Row Column with the following \ncharacteristics:\n\n" &
"   - this widget has 9 children: A label,\n     a PushButton, a pushButtonGadget,\n     a ToggleButton, a ToggleButtonGadget," &
"\n     a Scale, a scrollBar, an arrowButton,\n     and a arrowButton gadget\n" &
"   - background is steelblue" &
"\n   - foreground is black\n   - borderWidth is 1\n   - resizeWidth is false\n" &
"   - width is 300, height is 400\n   - packing is XmTIGHT\n" &
"   - resizeHeight is false\n   - marginHeight is 30\n   - marginWidth is 30\n   - spac" &
"ing is 20\n   - entryborder is 4\n   - entryCallback is ON\n\nAll other resources are set" &
" by default.\n";
