! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a scale widget with the \nfollowing characteristics:\n\n   - X and Y are 80\n" &
	"   - value is 60\n   - maximum is 250\n   - showVal" &
	"ue is true\n   - scaleWidth is 20\n   - scaleHeight is 100\n" &
	"   - valueChangedCallback is ON\n\n" &
	"Automatically Created widget resources:\n\n" &
	"   - labelString for title label is\n" &
	"     The Verical Scale\n" &
	"   - title label's fontList is variable\n\n" &
	"All other resources are set by default.\n";
