! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a ScrolledList with the\nfollowing characteristics:\n\n   - listMarginWidth" &
" is 10\n   - listMarginHeight is 10\n   - listSpacing is 10\n   - items are item1 ." &
".. item7\n   - itemCount is 7\n   - selectedItemCount is 2\n   - selectedItems are " &
"item1 \n     and item7\n   - visibleItemsCount is 4\n   - fontList is 9x15\n   - selectionPolicy is \n     " &
"XmSINGLE_SELECT\n   - singleSelectCallback is ON\n   - listSizePolicy is\n     XmRESIZE_IF_POSSIBLE\n" &
"\nAll other resources are set by " &
"default.\n";
