! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a scrolledWindow with the\nfollowing characteristics:\n" &
"\n   - a list is placed in the window\n     with 10 elements\n" &
"   - borderWidth is 4\n   - width is 150\n   - height is 150\n   - background is white\n   - foreground is black\n" &
"   - scrollBarPlacement is XmBOTTOM_LEFT\n   - scrollBarDisplayPolicy is XMSTATIC\n" &
"   - fontList is 8x13bold\n" &
"   - scrollingPolicy is XmAUTOMATIC\n   - scrolledWindowMarginWidth and\n     scrolledWindowHeight are 5\n" &
"\nAll other resources are set by default.\n";
