! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is two Scrolled Lists contained in a form\n" &
	"with the following characteristics:\n\n" &
	"   - ScrollList1 is attached to the\n     Form on the left, bottom,\n     and the top\n" &
	"   - ScrollList2 is attached to the\n     Form on the right, bottom,\n     and the top\n" &
	"   - ScrollList2 is attached to List1\n     on the left\n" &
	"   - Width of the form is 200, height is 200\n" &
	"   - listMarginWidths are 10\n   - listMarginHeights are 10\n" &
	"   - listSpacings are 10\n   - items are item1 ." &
	".. item5\n   - itemCounts are 5\n" &
	"   - visibleItemsCounts are 4\n   - fontLists are variable\n" &
	"\nAll other resources are set by " &
	"default.\n";
