! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a selectionBox Dialog with the \nfollowing characteristics:\n\n   - borderWidth is" &
" 4\n   - background Color is cyan\n   - autoUnmanage is false\n   - noResize is true\n   - selectionLabelString" &
" is\n     Your Selection Please:\n   - textString is item3\n   - listItems are item1 ... item5\n" &
"   - applyCallback is ON\n   - okCallback is ON\n   - cancelCallba" &
"ck is ON\n   - helpCallback is ON\n\nAll other resources are set by default.\n";
