! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a text widget with the following\ncharacteristics:\n\n   - background is fo" &
"restGreen\n   - width is 300\n   - borderWidth is 8\n   - shadowThickness is 8\n   - topCharacter is 5\n" &
"   - autoShowCursorPosition is false\n   - editable is false\n" &
"   - motionVerifyCallback is ON\n   - activateCallback is ON\n   - wordWrap" &
" is true\n   - rows is 3\n   - blinkRate is 0\n   - fontList is variable_font\n   - editMode is \n " &
"    XmMULTI_LINE_EDIT\n"&
"   - selectionArray is XmSELECT_POSITION,\n"&
"                       XmSELECT_WORD\n\nAll other resources are set by default.\n";
