! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
 value
        message : "This is a toggleButton with the \nfollowing characteristics:\n\n   - borderWidth is" &
" 2\n   - background is turquoise\n   - selectColor is violet\n   - armCallback is O" &
"N\n   - disarmCallback is ON\n   - spacing is 15\n   - detailShadowThickness is 2\n   - highlightThickness is 5" &
"\n\n\nAll other resources are set by default.\n";















