.TH "XmCreateIconBox" "library call"
.SH "NAME"
\fBXmCreateIconBox\fP \(em The IconBox widget creation function
.iX "XmCreateIconBox"
.iX "creation functions" "XmCreateIconBox"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/IconBox\&.h>
\fBWidget \fBXmCreateIconBox\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\fBArgList \fBarglist\fR\fR,
\fBCardinal \fBargcount\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmCreateIconBox\fP creates an instance of a IconBox widget and returns the
associated widget ID\&.
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP "\fIarglist\fP" 10
Specifies the argument list\&.
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list
(\fIarglist\fP)\&.
.SH "RETURN"
.PP
Returns the IconBox widget ID\&.
.SH "RELATED"
.PP
\fBXmIconBox\fP(3) and \fBXtCreateWidget\fP(3)\&.
