.TH "XmCreateTabStack" "library call"
.SH "NAME"
\fBXmCreateTabStack\fP \(em The TabStack widget creation function
.iX "XmCreateTabStack"
.iX "creation functions" "XmCreateTabStack"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/TabStack\&.h>
\fBWidget \fBXmCreateTabStack\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\fBArgList \fBarglist\fR\fR,
\fBCardinal \fBargcount\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmCreateTabStack\fP creates an instance of a TabStack widget and returns the
associated widget ID\&.
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP "\fIarglist\fP" 10
Specifies the argument list\&.
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list
(\fIarglist\fP)\&.
.SH "RETURN"
.PP
Returns the TabStack widget ID\&.
.SH "RELATED"
.PP
\fBXmTabStack\fP(3), \fBXmVaCreateTabStack\fP(3) and \fBXtCreateWidget\fP(3)\&.
