.TH "XmCreatePaned" "library call"
.SH "NAME"
\fBXmCreatePaned\fP \(em The Paned widget creation function
.iX "XmCreatePaned"
.iX "creation functions" "XmCreatePaned"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/Paned\&.h>
\fBWidget \fBXmCreatePaned\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\fBArgList \fBarglist\fR\fR,
\fBCardinal \fBargcount\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmCreatePaned\fP creates an instance of a Paned widget and returns the
associated widget ID\&.
.IP "\fIparent\fP" 10
Specifies the parent widget ID\&.
.IP "\fIname\fP" 10
Specifies the name of the created widget\&.
.IP "\fIarglist\fP" 10
Specifies the argument list\&.
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list
(\fIarglist\fP)\&.
.SH "RETURN"
.PP
Returns the Paned widget ID\&.
.SH "RELATED"
.PP
\fBXmPaned\fP(3) and \fBXtCreateWidget\fP(3)\&.
