.TH "XmDropDownGetLabel" "library call"
.SH "NAME"
\fBXmDropDownGetLabel\fP \(em A DropDown function that returns its label child
.iX "XmDropDownGetLabel"
.iX "DropDown functions" "XmDropDownGetLabel"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DropDown\&.h>
\fBWidget \fBXmDropDownGetLabel\fP\fR(
\fBWidget \fBwidget\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmDropDownGetLabel\fP returns the label child of a DropDown\&. It is
equivalent to \fBXmDropDownGetChild\fP(\fIwidget\fP,
\fBXmDROPDOWN_LABEL\fP)\&.
.IP "\fIwidget\fP" 10
Specifies the DropDown widget ID\&.
.SH "RETURN"
.PP
Returns the widget ID of the label, or NULL if \fIwidget\fP is not a
DropDown\&. An application should not assume that the returned
widget is of any particular class\&.
.SH "RELATED"
.PP
\fBXmDropDown\fP(3) and \fBXmDropDownGetChild\fP(3)\&.
