.TH "XmeClearBorder" "library call"
.nh
.SH "NAME"
\fB\%XmeClearBorder\fP \(em A widget writer function that clears the border of a rectangle
.iX "XmeClearBorder"
.iX "Xme draw functions" "XmeClearBorder"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DrawP\&.h>
\fBvoid \fBXmeClearBorder\fP\fR(
\fBDisplay *\fBdisplay\fR\fR,
\fBWindow \fBw\fR\fR,
\fBPosition \fBx\fR\fR,
\fBPosition \fBy\fR\fR,
\fBDimension \fBwidth\fR\fR,
\fBDimension \fBheight\fR\fR,
\fBDimension \fBshadow_thick\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fB\%XmeClearBorder\fP clears, with \fB\%XClearArea\fP and without
generating
exposures, a band of thickness \fIshadow_thick\fP along the inside of
the rectangle \fIx\fP, \fIy\fP, \fIwidth\fP, \fIheight\fP of the window
\fIw\fP\&.  A widget
uses it to erase the shadow or the highlight it drew with
\fB\%XmeDrawShadows\fP or \fB\%XmeDrawHighlight\fP, for instance when it
loses
the focus\&.  Nothing is done if \fIw\fP is None or if
\fIshadow_thick\fP,
\fIwidth\fP or \fIheight\fP is 0\&.
.IP "\fIdisplay\fP" 10
Specifies the display\&.
.IP "\fIw\fP" 10
Specifies the window\&.
.IP "\fIx\fP" 10
Specifies the x coordinate of the rectangle\&.
.IP "\fIy\fP" 10
Specifies the y coordinate of the rectangle\&.
.IP "\fIwidth\fP" 10
Specifies the width of the rectangle\&.
.IP "\fIheight\fP" 10
Specifies the height of the rectangle\&.
.IP "\fIshadow_thick\fP" 10
Specifies the thickness of the band to clear\&.
.PP
Motif 1\&.2 called this function \fB\%_XmClearBorder\fP\&.  The library
still exports that name for old binaries, and \fB\%<Xm/XmP\&.h>\fP
defines it as a macro for \fB\%XmeClearBorder\fP unless
\fB\%NO_XM_1_2_BC\fP is defined; new code should use
\fB\%XmeClearBorder\fP\&.
.SH "RELATED"
.PP
\fB\%XmeDrawShadows\fP(3) and \fB\%XmeDrawHighlight\fP(3)\&.
