.TH "XmeConfigureObject" "library call"
.nh
.SH "NAME"
\fB\%XmeConfigureObject\fP \(em A widget writer function that moves and resizes a widget or gadget
.iX "XmeConfigureObject"
.iX "Xme functions" "XmeConfigureObject"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/XmP\&.h>
\fBvoid \fBXmeConfigureObject\fP\fR(
\fBWidget \fBg\fR\fR,
\fBPosition \fBx\fR\fR,
\fBPosition \fBy\fR\fR,
\fBDimension \fBwidth\fR\fR,
\fBDimension \fBheight\fR\fR,
\fBDimension \fBborder_width\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fB\%XmeConfigureObject\fP is the function a Motif geometry manager uses
to move and resize one of its children, widget or gadget\&.  It calls
\fB\%XtConfigureWidget\fP between \fB\%XmDropSiteStartUpdate\fP and
\fB\%XmDropSiteEndUpdate\fP, so that the drop sites of the child follow
it\&.
.PP
If both \fIwidth\fP and \fIheight\fP are 0, the child is given the width
and
height it prefers (\fB\%XtQueryGeometry\fP)\&.  A width or height that
is
still 0 is made 1, since X does not allow empty windows\&.
.IP "\fIg\fP" 10
Specifies the widget or gadget to configure\&.
.IP "\fIx\fP" 10
Specifies the new x coordinate\&.
.IP "\fIy\fP" 10
Specifies the new y coordinate\&.
.IP "\fIwidth\fP" 10
Specifies the new width\&.
.IP "\fIheight\fP" 10
Specifies the new height\&.
.IP "\fIborder_width\fP" 10
Specifies the new border width\&.
.PP
Motif 1\&.2 called this function \fB\%_XmConfigureObject\fP\&.  The
library still exports that name for old binaries, and
\fB\%<Xm/XmP\&.h>\fP defines it as a macro for
\fB\%XmeConfigureObject\fP unless \fB\%NO_XM_1_2_BC\fP is defined; new
code should use \fB\%XmeConfigureObject\fP\&.
.SH "RELATED"
.PP
\fB\%XtConfigureWidget\fP(3), \fB\%XmDropSiteStartUpdate\fP(3) and
\fB\%XmeReplyToQueryGeometry\fP(3)\&.
