.TH "XmeDrawSeparator" "library call"
.nh
.SH "NAME"
\fBXmeDrawSeparator\fP \(em A widget writer function that draws a separator line
.iX "XmeDrawSeparator"
.iX "Xme draw functions" "XmeDrawSeparator"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DrawP\&.h>
\fBvoid \fBXmeDrawSeparator\fP\fR(
\fBDisplay *\fBdisplay\fR\fR,
\fBDrawable \fBd\fR\fR,
\fBGC \fBtop_gc\fR\fR,
\fBGC \fBbottom_gc\fR\fR,
\fBGC \fBseparator_gc\fR\fR,
\fBPosition \fBx\fR\fR,
\fBPosition \fBy\fR\fR,
\fBDimension \fBwidth\fR\fR,
\fBDimension \fBheight\fR\fR,
\fBDimension \fBshadow_thick\fR\fR,
\fBDimension \fBmargin\fR\fR,
\fBunsigned char \fBorientation\fR\fR,
\fBunsigned char \fBseparator_type\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmeDrawSeparator\fP draws a separator line of type
\fIseparator_type\fP
across the middle of the rectangle \fIx\fP, \fIy\fP, \fIwidth\fP,
\fIheight\fP of the
drawable \fId\fP, as the Separator widget and gadget do\&.  A horizontal
separator runs from \fImargin\fP pixels after the left side to
\fImargin\fP
pixels before the right side; a vertical one, likewise, between the
top and the bottom\&.
.PP
The single and double line types are drawn with \fIseparator_gc\fP; the
double lines are 2 pixels apart\&.  The shadowed types are drawn with
\fItop_gc\fP and \fIbottom_gc\fP, exchanged for the etched-in types, and
need
a non-zero \fIshadow_thick\fP; the dashed shadowed types use dashes
three
times the shadow thickness long\&.  Nothing is drawn for \fBXmNO_LINE\fP
or
if \fId\fP is None\&.
.IP "\fIdisplay\fP" 10
Specifies the display\&.
.IP "\fId\fP" 10
Specifies the drawable to draw into\&.
.IP "\fItop_gc\fP" 10
Specifies the top shadow GC of the shadowed types\&.
.IP "\fIbottom_gc\fP" 10
Specifies the bottom shadow GC of the shadowed types\&.
.IP "\fIseparator_gc\fP" 10
Specifies the GC of the single and double line types; a dashed type
needs a GC with a dashed line style\&.
.IP "\fIx\fP" 10
Specifies the x coordinate of the rectangle\&.
.IP "\fIy\fP" 10
Specifies the y coordinate of the rectangle\&.
.IP "\fIwidth\fP" 10
Specifies the width of the rectangle\&.
.IP "\fIheight\fP" 10
Specifies the height of the rectangle\&.
.IP "\fIshadow_thick\fP" 10
Specifies the thickness of the shadowed types\&.
.IP "\fImargin\fP" 10
Specifies the space left at both ends of the line\&.
.IP "\fIorientation\fP" 10
Specifies \fBXmHORIZONTAL\fP or \fBXmVERTICAL\fP\&.
.IP "\fIseparator_type\fP" 10
Specifies \fBXmNO_LINE\fP, \fBXmSINGLE_LINE\fP,
\fBXmDOUBLE_LINE\fP, \fBXmSINGLE_DASHED_LINE\fP,
\fBXmDOUBLE_DASHED_LINE\fP,
\fBXmSHADOW_ETCHED_IN\fP, \fBXmSHADOW_ETCHED_OUT\fP,
\fBXmSHADOW_ETCHED_IN_DASH\fP
or \fBXmSHADOW_ETCHED_OUT_DASH\fP, as for the \fBXmNseparatorType\fP
resource
of \fBXmSeparator\fP(3)\&.
.PP
Motif 1\&.2 called this function \fB_XmDrawSeparator\fP\&.  The library
still exports that name for old binaries, and \fB<Xm/XmP\&.h>\fP defines
it as a macro for \fBXmeDrawSeparator\fP unless \fBNO_XM_1_2_BC\fP is
defined; new code should use \fBXmeDrawSeparator\fP\&.
.SH "RELATED"
.PP
\fBXmSeparator\fP(3), \fBXmSeparatorGadget\fP(3) and
\fBXmeDrawShadows\fP(3)\&.
