.TH "XmeDrawHighlight" "library call"
.nh
.SH "NAME"
\fBXmeDrawHighlight\fP \(em A widget writer function that draws the highlight border of a rectangle
.iX "XmeDrawHighlight"
.iX "Xme draw functions" "XmeDrawHighlight"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/DrawP\&.h>
\fBvoid \fBXmeDrawHighlight\fP\fR(
\fBDisplay *\fBdisplay\fR\fR,
\fBDrawable \fBd\fR\fR,
\fBGC \fBgc\fR\fR,
\fBPosition \fBx\fR\fR,
\fBPosition \fBy\fR\fR,
\fBDimension \fBwidth\fR\fR,
\fBDimension \fBheight\fR\fR,
\fBDimension \fBhighlight_thick\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmeDrawHighlight\fP fills, with \fIgc\fP, a band of thickness
\fIhighlight_thick\fP along the inside of the rectangle \fIx\fP,
\fIy\fP,
\fIwidth\fP, \fIheight\fP of the drawable \fId\fP\&.  Primitive widgets
draw their
keyboard focus highlight this way, with the GC of the
\fBXmNhighlightColor\fP resource, and erase it with
\fBXmeClearBorder\fP\&.  Nothing is drawn if \fId\fP is None or if
\fIhighlight_thick\fP, \fIwidth\fP or \fIheight\fP is 0\&.
.IP "\fIdisplay\fP" 10
Specifies the display\&.
.IP "\fId\fP" 10
Specifies the drawable to draw into\&.
.IP "\fIgc\fP" 10
Specifies the GC of the highlight\&.
.IP "\fIx\fP" 10
Specifies the x coordinate of the rectangle\&.
.IP "\fIy\fP" 10
Specifies the y coordinate of the rectangle\&.
.IP "\fIwidth\fP" 10
Specifies the width of the rectangle\&.
.IP "\fIheight\fP" 10
Specifies the height of the rectangle\&.
.IP "\fIhighlight_thick\fP" 10
Specifies the thickness of the highlight, in pixels\&.
.PP
Motif 1\&.2 called this function \fB_XmDrawSimpleHighlight\fP\&.  The
library still exports that name for old binaries, and \fB<Xm/XmP\&.h>\fP
defines it as a macro for \fBXmeDrawHighlight\fP unless
\fBNO_XM_1_2_BC\fP is defined; new code should use
\fBXmeDrawHighlight\fP\&.
.SH "RELATED"
.PP
\fBXmeClearBorder\fP(3), \fBXmeDrawShadows\fP(3) and
\fBXmPrimitive\fP(3)\&.
