.TH "XmeTransferAddDoneProc" "library call"
.nh
.SH "NAME"
\fB\%XmeTransferAddDoneProc\fP \(em A widget writer function that adds a procedure to call when a transfer ends
.iX "XmeTransferAddDoneProc"
.iX "Xme transfer functions" "XmeTransferAddDoneProc"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/TransferP\&.h>
\fBvoid \fBXmeTransferAddDoneProc\fP\fR(
\fBXtPointer \fBtransfer_id\fR\fR,
\fBXmSelectionFinishedProc \fBdone_proc\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fB\%XmeTransferAddDoneProc\fP adds \fIdone_proc\fP to the procedures
that are
called, in the order they were added, when the data transfer
\fItransfer_id\fP finishes\&.  The destination procedure of a widget
uses it
to free what it allocated for the transfer, or to do the work that
needs all the data, for instance deleting the source of a move\&.  It is
called as:
.PP
.nf
void (*done_proc)(Widget w, XtEnum op,
                  XmTransferDoneCallbackStruct *ts);
.fi
.PP
where \fIw\fP is the destination widget, \fIop\fP the operation of the
transfer and \fIts\fP gives its status\&.
.IP "\fItransfer_id\fP" 10
Specifies the transfer, the \fB\%transfer_id\fP of the
\fB\%XmDestinationCallbackStruct\fP\&.
.IP "\fIdone_proc\fP" 10
Specifies the procedure\&.
.SH "RELATED"
.PP
\fB\%XmTransferValue\fP(3), \fB\%XmTransferDone\fP(3) and
\fB\%XmeStandardConvert\fP(3)\&.
