.TH "XmMultiListUnselectItem" "library call"
.SH "NAME"
\fBXmMultiListUnselectItem\fP,
\fBXmExt18ListUnselectItem\fP \(em MultiList functions that deselect the specified item of the list
.iX "XmMultiListUnselectItem"
.iX "XmExt18ListUnselectItem"
.iX "Extended List functions" "XmMultiListUnselectItem"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBvoid \fBXmMultiListUnselectItem\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXmMultiListRowInfo *\fBrow_info\fR\fR);
.PP
#include <Xm/Ext18List\&.h>
\fBvoid \fBXmExt18ListUnselectItem\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBXm18RowInfo *\fBrow_info\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmMultiListUnselectItem\fP unselects the row designated by
row_info of the passed MultiList widget\&.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList from whose list an item is unselected\&.
.IP "\fIrow_info\fP" 10
Specified the pointer to the row which is to be unselected\&.
.PP
For a complete definition of MultiList and its associated resources,
see \fBXmMultiList\fP(3)\&.
.PP
\fBXmExt18ListUnselectItem\fP is the obsolete name of \fBXmMultiListUnselectItem\fP, from the time
the MultiList was called the Ext18List; \fB<Xm/Ext18List\&.h>\fP
declares it deprecated\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
