.TH "XmMultiListGetSelectedRowArray" "library call"
.SH "NAME"
\fBXmMultiListGetSelectedRowArray\fP,
\fBXmExt18ListGetSelectedRowArray\fP \(em MultiList functions that return an array
of integers which are selected row numbers.
.iX "XmMultiListGetSelectedRowArray"
.iX "XmExt18ListGetSelectedRowArray"
.iX "List functions" "XmMultiListGetSelectedRowArray"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBint *\fBXmMultiListGetSelectedRowArray\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBint *\fBnum_rows\fR\fR);
.PP
#include <Xm/Ext18List\&.h>
\fBint *\fBXmExt18ListGetSelectedRowArray\fP\fR(
\fBWidget \fBwidget\fR\fR,
\fBint *\fBnum_rows\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
This routine creates an array of integers which are selected row numbers in the
MultiList widget.
.IP "\fIwidget\fP" 10
Specifies the ID of the MultiList widget\&.
.IP "\fInum_rows\fP" 10
Specifies pointer to the integer indicates number of returned row numbers.
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.PP
\fBXmExt18ListGetSelectedRowArray\fP is the obsolete name of \fBXmMultiListGetSelectedRowArray\fP, from the time
the MultiList was called the Ext18List; \fB<Xm/Ext18List\&.h>\fP
declares it deprecated\&.
.SH "RETURN"
.PP
The \fBint *\fR returned by this function contains a selected rows numbers array.
The calling routine is responsible for freeing the returned pointer with XtFree()\&.
The function will return NULL if no elements are selected\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
