! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
value
  message :
	"The following is a Bulletin Board set up to test correct\n" &
	"handling of gadget specification syntax. The bulletin board\n" &
	"contains two of each supported gadget. The module header for\n" &
	"this test specifies the gadget variant for each object\n" &
	"supporting a gadget variant. Thus the gadget in the left\n" &
	"column was specified with Xm<type> syntax. The gadget in\n" &
	"the right column was specified with Xm<type>Gadget syntax.\n" &
	"The CascadeButton gadgets are contained in a MenuBar.\n\n" &
	"A Message stating that the callback reason for\n" &
	"MrmNcreateCallback is 43 should be printed in the\n" &
	"term window";
