#!/bin/bash

# Script to generate Xm string definition files
set -e

SOURCE_DIR="$1"
BUILD_DIR="$2"
MAKESTRS="$3"

if [ -z "$SOURCE_DIR" ] || [ -z "$BUILD_DIR" ] || [ -z "$MAKESTRS" ]; then
    echo "Usage: $0 <source_dir> <build_dir> <makestrs_path>"
    exit 1
fi

# Create directories
mkdir -p "$BUILD_DIR/src/lib/Xm"
mkdir -p "$BUILD_DIR/include/Xm"

# Copy template files
cp -f "$SOURCE_DIR/src/lib/Xm/XmStrDefs.ht" "$BUILD_DIR/src/lib/Xm/"
cp -f "$SOURCE_DIR/src/lib/Xm/XmStrDefs22.ht" "$BUILD_DIR/src/lib/Xm/"
cp -f "$SOURCE_DIR/src/lib/Xm/XmStrDefs23.ht" "$BUILD_DIR/src/lib/Xm/"
cp -f "$SOURCE_DIR/src/lib/Xm/XmStrDefsI.ht" "$BUILD_DIR/src/lib/Xm/"
cp -f "$SOURCE_DIR/src/lib/Xm/XmStrDefs.ct" "$BUILD_DIR/src/lib/Xm/"

# Generate string files
cd "$BUILD_DIR/src/lib/Xm"
"$MAKESTRS" -f xmstring.list > XmStrDefs.c 2>/dev/null

# The makestrs tool should generate the header files directly
# Check if header files were generated, if not, create them from templates
if [ ! -f "XmStrDefs.h" ] || [ ! -s "XmStrDefs.h" ]; then
    sed 's/<<<STRING_TABLE_GOES_HERE>>>/extern char *XmStrings[];/' XmStrDefs.ht > XmStrDefs.h
fi
if [ ! -f "XmStrDefs22.h" ] || [ ! -s "XmStrDefs22.h" ]; then
    sed 's/<<<STRING_TABLE_GOES_HERE>>>/extern char *XmStrings22[];/' XmStrDefs22.ht > XmStrDefs22.h
fi
if [ ! -f "XmStrDefs23.h" ] || [ ! -s "XmStrDefs23.h" ]; then
    sed 's/<<<STRING_TABLE_GOES_HERE>>>/extern char *XmStrings23[];/' XmStrDefs23.ht > XmStrDefs23.h
fi
if [ ! -f "XmStrDefsI.h" ] || [ ! -s "XmStrDefsI.h" ]; then
    sed 's/<<<STRING_TABLE_GOES_HERE>>>/extern char *XmStringsI[];/' XmStrDefsI.ht > XmStrDefsI.h
fi

# Copy generated files to include directory
cp -f XmStrDefs.h "$BUILD_DIR/include/Xm/"
cp -f XmStrDefs22.h "$BUILD_DIR/include/Xm/"
cp -f XmStrDefs23.h "$BUILD_DIR/include/Xm/"
cp -f XmStrDefsI.h "$BUILD_DIR/include/Xm/"

# Copy generated .c file to lib directory (it stays in lib/Xm)
# The .c file is needed for compilation and should remain in the lib directory

# XmMsgCatI.h is generated by its own rule in src/lib/Xm/CMakeLists.txt
# (motif_add_message_catalog, or the stub copy without message catalogs).

# Generated Xm string definition files successfully
