! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
!
value
  message :
	"Enumerated Values Test 2:\n\n" &
	"The following is a Bulletin Board set up to test correct\n" &
	"usage of enumeration values. (Note: this explanation text\n" &
	"itself tests the following:\n" &
	"  - XmNeditMode = XmMULTI_LINE_EDIT\n" &
	"Bulletin Board characteristics:\n" &
	"  - XmNborderWidth = 1\n" &
	"  - XmNbackground =  sky_blue\n" &
	"  - XmNmarginWidth =  20\n" &
	"  - XmNmarginHeight =  20\n" &
	"  - XmNdefaultPosition =  false\n" &
	"  - XmNnoResize =  true\n" &
	"  - XmNResizePolicy = XmRESIZE_GROW\n" &
	"  - XmNshadowType = XmSHADOW_ETCHED_OUT\n" &
	"  - XmNshadowThickness = 10\n" &
	"Label characeristics:\n" &
	"  - XmNunitType = Xm100TH_MILLIMETERS\n" &
	"  - XmNx = 1000\n" &
	"  - XmNy = 1000\n" &
	"  - XmNwidth = 6000\n" &
	"  - XmNalignment = align_value = XmALIGNMENT_END\n" &
	"  - XmNlabelString = Label 1\n" &
	"  - XmNstringDirection = XmSTRING_DIRECTION_L_TO_R\n" &
	"Separator characteristics:\n" &
	"  - XmNunitType = Xm1000TH_INCHES\n" &
	"  - XmNx = 394\n" &
	"  - XmNy = 900\n" &
	"  - XmNwidth = 4000\n" &
	"  - XmNseparatorType = XmDOUBLE_DASHED_LINE\n";
