! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
! 
!
 value
        message : "This is a pushButton widget with the \nfollowing charcteristics:\n\n" &
"   - unitType is Xm100TH_MILLIMETERS\n   - width and height are 3500\n" &
"   - background color is Orange\n   - traversalOn is true\n   -" &
" highlightThickness is 100\n   - highlightColor is navy\n" &
"   - shadowThickness is 100\n   - marginWidth and marginHeight\n     are 0\n" &
"   - armColor is green\n   - armCallback and disarmCallbacks\n     are ON\n" &
"   - highlightOnEnter is true\n" &
"   - fontList is 8x13bold" &
"\n\nAll other resources are set by default.\n";
