$ $XConsortium: Uil.msg /main/4 1996/08/19 11:53:43 pascale $
$set 1

1 duplicate option \"%s\" was ignored
2 unknown option \"%s\" was ignored
3 additional UIL source file: %s was ignored
4 error opening source file: %s
5 error reading next line of source file: %s
6 Internal error: %s
7 line truncated at %d characters
8 value of %s is out of range %s
9 %s not terminated %s
10 unprintable character \\%d\\ ignored
11 unknown sequence \"%s\" ignored
12 unknown escape sequence \"\\%c\" - \\ ignored
13 name exceeds %d characters - truncated to: %s
14 compiler ran out of virtual memory
15 unexpected %s token found - parsing resumes after \"%c\"
16 %s %s must be defined before this reference
17 context requires a %s - %s was specified
18 %s is not implemented yet
19 found %s value when expecting %s value
20 the %s %s is not supported for the %s object
21 this %s %s supersedes a previous definition in this %s %s
22 name %s previously defined as %s
23 value used in this context must be private
24 procedure %s was previously declared with %d arguments
25 found %s value - procedure %s argument must be %s value
26 found %s %s when expecting %s %s
27 %s %s was never defined
28 %s %s already specified for this %s %s
29 %s item not allowed in %s %s
30 compilation terminated - please fix previous errors
31 internal error - please submit defect report
32  
33 %s missing following \"%s\" option
34 error opening listing file: %s
35 error writing to listing file: %s
36 invalid module structure - check UIL module syntax
37 too many source files open: %s
38 source line contains a null character
39 errors: %d  warnings: %d  informationals: %d
40 error opening UID file: %s
41 no UID file was produced
42 creation procedure is not supported by the %s widget
43 creation procedure is not allowed in a %s widget reference
44 creation procedure is required in a %s widget declaration
45 a NULL character in a string is not supported
46 widget %s is part of a circular definition
47 no source file specified
48 %s %s supports only a single %s %s
49 %s widget supports only a single control
50 unknown character set
51 place names clause before other module clauses
52 color letter string must be a single character
53 color letter used for prior color in this table
54 row %d must have same width as row 1
55 row %d, column %d: letter \"%c\" not in color table
56 too many %ss in %s, limit is %d
57 Subqualifier not allowed with negated qualifier
58 %s gadget is not supported - %s widget will be used instead
59 %s type is not valid for %s
60 support for this character set may be removed in a future release
61 the %s constraint is not supported for the %s %s
62 too many \"%s\" options, limit is %d
63 error closing source file: %s
64 the %s value is circularly defined
65 overriding built-in name %s
66 the %s argument does not support enumerated values
67 the %s argument does not support the %s enumerated value
68 $LANG contains an unknown character set
69 the %s object's controls hierarchy contains a reference to itself
70 value %s is too large for context buffer
71 forward referencing is not allowed for %s
72 cannot convert %s type to %s type
73 %s is invalid
74 error reading binary database
75 binary database compiled with a future version
76 error opening database file: %s
77 error writing UID file: %s
78 '%s' is an unknown Toolkit class record name
79 invalid include file name
80 incompatible unit types for arithmetic operation
81 %s used as charset name; %s used as charset component

$set 2
1 ** error **
2 ** unknown **

$set 3

1 Info: 
2 Warning: 
3 Error: 
4 Severe: 
5 \t\t line: %d  file: %s
6 \t\t line: %d  position: %d  file: %s
