name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, x86]
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Alpine
        id:   alpine
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}
          branch: v3.22
          packages: >
            libx11-dev
            libxpm-dev
            libxt-dev
            libxmu-dev
            libxext-dev
            libxft-dev
            libjpeg-turbo-dev
            libpng-dev
            linux-headers
            alpine-sdk
            autoconf
            autoconf-archive
            automake
            libtool
            flex-dev
            flex
            byacc
            xvfb
            xbitmaps
            check-dev
            clang
            clang-dev
      - name: Make
        run: |
          cd /home/runner/work/motif/motif
          CC=${{ matrix.compiler }} ./autogen.sh --enable-tests
          make
        shell: alpine.sh {0}
      - name: Test
        run: |
          cd /home/runner/work/motif/motif
          Xvfb :0 &>/dev/null &
          DISPLAY=:0 make check
          kill -TERM %1
        shell: alpine.sh {0}

